/* This file is part of the db4o object database http://www.db4o.com

Copyright (C) 2004 - 2011  Versant Corporation http://www.versant.com

db4o is free software; you can redistribute it and/or modify it under
the terms of version 3 of the GNU General Public License as published
by the Free Software Foundation.

db4o is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License along
with this program.  If not, see http://www.gnu.org/licenses/. */
namespace OmControlLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_jp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_jp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmControlLibrary.Resources.Resource.jp", typeof(Resource_jp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute List.
        /// </summary>
        internal static string ATTRIB_TEXT {
            get {
                return ResourceManager.GetString("ATTRIB_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp;Group.
        /// </summary>
        internal static string BUTTON_ADD_GROUP_CAPTION {
            get {
                return ResourceManager.GetString("BUTTON_ADD_GROUP_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear All.
        /// </summary>
        internal static string BUTTON_CLEAR_AAL_CAPTION {
            get {
                return ResourceManager.GetString("BUTTON_CLEAR_AAL_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string BUTTON_DELETE_CAPTION {
            get {
                return ResourceManager.GetString("BUTTON_DELETE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string BUTTON_SAVE_CAPTION {
            get {
                return ResourceManager.GetString("BUTTON_SAVE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Update Query.
        /// </summary>
        internal static string BUTTON_UPDATE_QUERY_CAPTION {
            get {
                return ResourceManager.GetString("BUTTON_UPDATE_QUERY_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType.
        /// </summary>
        internal static string CLASS_PROPERTY_DATA_TYPE {
            get {
                return ResourceManager.GetString("CLASS_PROPERTY_DATA_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string CLASS_PROPERTY_FIELD_NAME {
            get {
                return ResourceManager.GetString("CLASS_PROPERTY_FIELD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexed.
        /// </summary>
        internal static string CLASS_PROPERTY_ISINDEXED {
            get {
                return ResourceManager.GetString("CLASS_PROPERTY_ISINDEXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string CLASS_PROPERTY_ISPUBLIC {
            get {
                return ResourceManager.GetString("CLASS_PROPERTY_ISPUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; select &gt;&gt;.
        /// </summary>
        internal static string COMBOBOX_DEFAULT_TEXT {
            get {
                return ResourceManager.GetString("COMBOBOX_DEFAULT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to logout?.
        /// </summary>
        internal static string CONFIRMATION_MSG_LOGOUT {
            get {
                return ResourceManager.GetString("CONFIRMATION_MSG_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the Expression Group?.
        /// </summary>
        internal static string CONFIRMATION_MSG_REMOVE_QUERY_GROUP {
            get {
                return ResourceManager.GetString("CONFIRMATION_MSG_REMOVE_QUERY_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Attributes List.
        /// </summary>
        internal static string CONTEXT_MENU_ADD_TO_ATTRIBUTE {
            get {
                return ResourceManager.GetString("CONTEXT_MENU_ADD_TO_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Query.
        /// </summary>
        internal static string CONTEXT_MENU_ADD_TO_QUERY {
            get {
                return ResourceManager.GetString("CONTEXT_MENU_ADD_TO_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Objects.
        /// </summary>
        internal static string CONTEXT_MENU_SHOW_ALL_OBJECTS {
            get {
                return ResourceManager.GetString("CONTEXT_MENU_SHOW_ALL_OBJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Classes.
        /// </summary>
        internal static string DB_PROPERTY_CLASSES {
            get {
                return ResourceManager.GetString("DB_PROPERTY_CLASSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Space.
        /// </summary>
        internal static string DB_PROPERTY_FREESPACE {
            get {
                return ResourceManager.GetString("DB_PROPERTY_FREESPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Size.
        /// </summary>
        internal static string DB_PROPERTY_SIZE {
            get {
                return ResourceManager.GetString("DB_PROPERTY_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to db4o Browser.
        /// </summary>
        internal static string DB4O_BROWSER_CAPTION {
            get {
                return ResourceManager.GetString("DB4O_BROWSER_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in connection!.
        /// </summary>
        internal static string ERROR_MSG_CONNECTION {
            get {
                return ResourceManager.GetString("ERROR_MSG_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string GUID_FORMATTER_STRING {
            get {
                return ResourceManager.GetString("GUID_FORMATTER_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Query.
        /// </summary>
        internal static string LABEL_QUERY_BUILDER {
            get {
                return ResourceManager.GetString("LABEL_QUERY_BUILDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Queries.
        /// </summary>
        internal static string LABEL_RECENT_QUERIES {
            get {
                return ResourceManager.GetString("LABEL_RECENT_QUERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Connect.
        /// </summary>
        internal static string LOGIN_CAPTION_CONNECT {
            get {
                return ResourceManager.GetString("LOGIN_CAPTION_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string LOGIN_CAPTION_LOCAL {
            get {
                return ResourceManager.GetString("LOGIN_CAPTION_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string LOGIN_CAPTION_OPEN {
            get {
                return ResourceManager.GetString("LOGIN_CAPTION_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string LOGIN_FILE_TEXT {
            get {
                return ResourceManager.GetString("LOGIN_FILE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string LOGIN_HOST_TEXT {
            get {
                return ResourceManager.GetString("LOGIN_HOST_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Connection.
        /// </summary>
        internal static string LOGIN_NEWCONNECTION_TEXT {
            get {
                return ResourceManager.GetString("LOGIN_NEWCONNECTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open db4o Database File.
        /// </summary>
        internal static string LOGIN_OPEN_FILE_DIALOG_CAPTION {
            get {
                return ResourceManager.GetString("LOGIN_OPEN_FILE_DIALOG_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LOGIN_PASSWORD_TEXT {
            get {
                return ResourceManager.GetString("LOGIN_PASSWORD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string LOGIN_PORT_TEXT {
            get {
                return ResourceManager.GetString("LOGIN_PORT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Connections.
        /// </summary>
        internal static string LOGIN_RECENTCONNECTION_TEXT {
            get {
                return ResourceManager.GetString("LOGIN_RECENTCONNECTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Type.
        /// </summary>
        internal static string LOGIN_TYPE_TEXT {
            get {
                return ResourceManager.GetString("LOGIN_TYPE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string LOGIN_USERNAME_TEXT {
            get {
                return ResourceManager.GetString("LOGIN_USERNAME_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to db4o database.
        /// </summary>
        internal static string LOGIN_WINDOW_LOCAL_CAPTION {
            get {
                return ResourceManager.GetString("LOGIN_WINDOW_LOCAL_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to db4o server.
        /// </summary>
        internal static string LOGIN_WINDOW_REMOTE_CAPTION {
            get {
                return ResourceManager.GetString("LOGIN_WINDOW_REMOTE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to db4o Browser Search.
        /// </summary>
        internal static string OBJBROWSER_FIND_TEXT {
            get {
                return ResourceManager.GetString("OBJBROWSER_FIND_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        internal static string OBJECT_PROPERTY_DEPTH {
            get {
                return ResourceManager.GetString("OBJECT_PROPERTY_DEPTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalID.
        /// </summary>
        internal static string OBJECT_PROPERTY_LOCALID {
            get {
                return ResourceManager.GetString("OBJECT_PROPERTY_LOCALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UUID.
        /// </summary>
        internal static string OBJECT_PROPERTY_UUID {
            get {
                return ResourceManager.GetString("OBJECT_PROPERTY_UUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string OBJECT_PROPERTY_VERSION {
            get {
                return ResourceManager.GetString("OBJECT_PROPERTY_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching objects found..
        /// </summary>
        internal static string OBJECTMANAGER_MSG_RESULT_NOT_FOUND {
            get {
                return ResourceManager.GetString("OBJECTMANAGER_MSG_RESULT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectManager Enterprise.
        /// </summary>
        internal static string PRODUCT_CAPTION {
            get {
                return ResourceManager.GetString("PRODUCT_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Credentials....
        /// </summary>
        internal static string PROGRESS_MESSAGE_CHECKING_CREDENTIALS {
            get {
                return ResourceManager.GetString("PROGRESS_MESSAGE_CHECKING_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Properties.
        /// </summary>
        internal static string PROPERTIES_TAB_CAPTION {
            get {
                return ResourceManager.GetString("PROPERTIES_TAB_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataBase Properties.
        /// </summary>
        internal static string PROPERTIES_TAB_DATABASE_CAPTION {
            get {
                return ResourceManager.GetString("PROPERTIES_TAB_DATABASE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Builder.
        /// </summary>
        internal static string QUERY_BUILDER_CAPTION {
            get {
                return ResourceManager.GetString("QUERY_BUILDER_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string QUERY_GRID_CONDITION {
            get {
                return ResourceManager.GetString("QUERY_GRID_CONDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string QUERY_GRID_FIELD {
            get {
                return ResourceManager.GetString("QUERY_GRID_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string QUERY_GRID_OPERATOR {
            get {
                return ResourceManager.GetString("QUERY_GRID_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string QUERY_GRID_VALUE {
            get {
                return ResourceManager.GetString("QUERY_GRID_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression Group .
        /// </summary>
        internal static string QUERY_GROUP_CAPTION {
            get {
                return ResourceManager.GetString("QUERY_GROUP_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties Pane.
        /// </summary>
        internal static string QUERY_RESULT_PROPERTIES_PANE_TEXT {
            get {
                return ResourceManager.GetString("QUERY_RESULT_PROPERTIES_PANE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Query Builder.
        /// </summary>
        internal static string QUERY_RESULT_SHOW_HIDE_QUERY_BUILDER {
            get {
                return ResourceManager.GetString("QUERY_RESULT_SHOW_HIDE_QUERY_BUILDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key: &lt;&lt;KEY&gt;&gt; does not exist in the resource file..
        /// </summary>
        internal static string RESOURCE_KEY_NOT_PRESENT {
            get {
                return ResourceManager.GetString("RESOURCE_KEY_NOT_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Columns.
        /// </summary>
        internal static string SHOW_ALL_COLUMN {
            get {
                return ResourceManager.GetString("SHOW_ALL_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string TOOLBAR_LOGIN_CAPTION {
            get {
                return ResourceManager.GetString("TOOLBAR_LOGIN_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string TOOLBAR_LOGOUT_CAPTION {
            get {
                return ResourceManager.GetString("TOOLBAR_LOGOUT_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Functionality Mode.
        /// </summary>
        internal static string TOOLBAR_MODE_FULL {
            get {
                return ResourceManager.GetString("TOOLBAR_MODE_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduced Mode.
        /// </summary>
        internal static string TOOLBAR_MODE_REDUCED {
            get {
                return ResourceManager.GetString("TOOLBAR_MODE_REDUCED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  can not be empty, enter some clauses..
        /// </summary>
        internal static string VALIDATION_DEFAULT_GROUP_IS_EMPTY {
            get {
                return ResourceManager.GetString("VALIDATION_DEFAULT_GROUP_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for some clauses are not specified yet..
        /// </summary>
        internal static string VALIDATION_MESSAGE_VALUE_NOT_SPECIFIED {
            get {
                return ResourceManager.GetString("VALIDATION_MESSAGE_VALUE_NOT_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter host..
        /// </summary>
        internal static string VALIDATION_MSG_ENTER_HOST {
            get {
                return ResourceManager.GetString("VALIDATION_MSG_ENTER_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password..
        /// </summary>
        internal static string VALIDATION_MSG_ENTER_PASSWORD {
            get {
                return ResourceManager.GetString("VALIDATION_MSG_ENTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter port..
        /// </summary>
        internal static string VALIDATION_MSG_ENTER_PORT {
            get {
                return ResourceManager.GetString("VALIDATION_MSG_ENTER_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter user name..
        /// </summary>
        internal static string VALIDATION_MSG_ENTER_USERNAME {
            get {
                return ResourceManager.GetString("VALIDATION_MSG_ENTER_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials don’t match. Please enter again..
        /// </summary>
        internal static string VALIDATION_MSG_INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("VALIDATION_MSG_INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value entered..
        /// </summary>
        internal static string VALIDATION_MSG_INVALIDE_VALUE {
            get {
                return ResourceManager.GetString("VALIDATION_MSG_INVALIDE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the database..
        /// </summary>
        internal static string VALIDATION_MSG_SELECT_DATABASE {
            get {
                return ResourceManager.GetString("VALIDATION_MSG_SELECT_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select remote connection..
        /// </summary>
        internal static string VALIDATION_MSG_SELECT_REMOTE_CONNECTION {
            get {
                return ResourceManager.GetString("VALIDATION_MSG_SELECT_REMOTE_CONNECTION", resourceCulture);
            }
        }
    }
}
